"""
graph/schema.py
===============
Creates all Neo4j constraints, indexes, and vector indexes.
Run once on startup — all operations use IF NOT EXISTS so safe to re-run.

Vector indexes use Neo4j 5.11+ built-in vector search (no external store needed).
Embeddings: nomic-embed-text via Ollama → 768 dimensions, cosine similarity.

Usage:
  python -m graph.schema
  -- or --
  from graph.schema import init_schema
  await init_schema(driver)
"""
import asyncio
import logging
import os

from neo4j import AsyncGraphDatabase

log = logging.getLogger("nathanai.crypto.graph.schema")

NEO4J_URI  = os.getenv("NEO4J_URI",      "bolt://neo4j:7687")
NEO4J_USER = os.getenv("NEO4J_USER",     "neo4j")
NEO4J_PASS = os.getenv("NEO4J_PASSWORD", "crypto123")

EMBEDDING_DIMS = 768          # nomic-embed-text output size
SIMILARITY_FN  = "cosine"    # cosine similarity for semantic search


# ── Constraints (uniqueness) ───────────────────────────────────────────────
CONSTRAINTS = [
    ("token_mint_unique",   "Token",     "mint"),
    ("wallet_addr_unique",  "Wallet",    "address"),
    ("signal_id_unique",    "Signal",    "id"),
    ("trade_id_unique",     "Trade",     "id"),
    ("news_ts_unique",      "NewsEvent", "id"),
]

# ── Standard indexes (range/lookup) ───────────────────────────────────────
INDEXES = [
    ("token_created_at",   "Token",     "created_at"),
    ("token_graduated",    "Token",     "graduated"),
    ("token_hard_skip",    "Token",     "rc_hard_skip"),
    ("token_ticker",       "Token",     "ticker"),
    ("wallet_grad_rate",   "Wallet",    "grad_rate"),
    ("signal_decision",    "Signal",    "decision"),
    ("signal_timestamp",   "Signal",    "timestamp"),
    ("trade_entry_time",   "Trade",     "entry_time"),
]

# ── Vector indexes (Neo4j 5.11+ built-in) ─────────────────────────────────
# Each node type that needs semantic similarity search gets a vector index.
# Embeddings generated by nomic-embed-text (768-dim) stored on the node.
VECTOR_INDEXES = [
    # Token context embedding — used for "find tokens similar to past graduates"
    # Input to embedder: "<name> <ticker> dev_grad_rate:<X> bc_pct:<Y> rc_score:<Z>"
    ("token_context_vector",  "Token",  "context_embedding"),

    # Wallet profile embedding — used for "find wallets similar to known smart money"
    # Input to embedder: "<address> launches:<N> grad_rate:<X> rugs:<Y>"
    ("wallet_profile_vector", "Wallet", "profile_embedding"),
]


async def init_schema(driver) -> None:
    """Create all constraints, indexes, and vector indexes. Safe to re-run."""
    async with driver.session() as session:

        # ── Constraints ────────────────────────────────────────────────────
        for name, label, prop in CONSTRAINTS:
            cypher = (
                f"CREATE CONSTRAINT {name} IF NOT EXISTS "
                f"FOR (n:{label}) REQUIRE n.{prop} IS UNIQUE"
            )
            await session.run(cypher)
            log.debug("constraint OK: %s", name)

        # ── Standard indexes ───────────────────────────────────────────────
        for name, label, prop in INDEXES:
            cypher = (
                f"CREATE INDEX {name} IF NOT EXISTS "
                f"FOR (n:{label}) ON (n.{prop})"
            )
            await session.run(cypher)
            log.debug("index OK: %s", name)

        # ── Vector indexes ─────────────────────────────────────────────────
        for name, label, prop in VECTOR_INDEXES:
            cypher = f"""
                CREATE VECTOR INDEX {name} IF NOT EXISTS
                FOR (n:{label}) ON (n.{prop})
                OPTIONS {{
                    indexConfig: {{
                        `vector.dimensions`:         {EMBEDDING_DIMS},
                        `vector.similarity_function`: '{SIMILARITY_FN}'
                    }}
                }}
            """
            await session.run(cypher)
            log.debug("vector index OK: %s", name)

        log.info(
            "Schema ready — %d constraints, %d indexes, %d vector indexes",
            len(CONSTRAINTS), len(INDEXES), len(VECTOR_INDEXES)
        )


async def verify_schema(driver) -> dict:
    """Return counts of each schema element — useful for health checks."""
    async with driver.session() as session:
        result = await session.run("SHOW INDEXES YIELD name, type, state")
        indexes = [dict(r) for r in await result.data()]

    vector = [i for i in indexes if i["type"] == "VECTOR"]
    online = [i for i in indexes if i["state"] == "ONLINE"]

    return {
        "total_indexes":  len(indexes),
        "vector_indexes": len(vector),
        "online_indexes": len(online),
        "vector_names":   [i["name"] for i in vector],
    }


async def main():
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s")
    driver = AsyncGraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASS))
    try:
        await init_schema(driver)
        status = await verify_schema(driver)
        print(f"\nSchema status: {status}")
    finally:
        await driver.close()


if __name__ == "__main__":
    asyncio.run(main())
